# Generated by Django 3.2.6 on 2021-08-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
